# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IBM Cloud Paks Playbook

# This is used next to the Bluemix logo at the top-left of the site.
logo_tag: IBM Cloud Pak

# NOTE: make sure there’s no trailing slash on your repo URL
github_repo:  https://github.com/ibm-cloud-architecture/cloudpak8s
github_branch: gh-pages

email: gangchen@us.ibm.com
description: > # this means to ignore newlines until "baseurl:"
  A centralized collection of best practices and guidelines for planning,
  implementing, and analyzing the data collected through Bluemix’s various
  analytics tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cloudpak8s.io" # the base hostname & protocol for your site, e.g. http://example.com

github:
  url: "https://cloudpak8s.io"

# Content settings
collections:
  content:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: page
      weight: 100

relative_links:
  enabled:     true
  collections: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-relative-links
exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - design
  - node_modules
  - bower.json
  - package.json
  - design
